// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASm9pcS1RBjSTtpoaVsRB8I9wb6aHRB2E',
    appId: '1:745130635449:web:70547ff72af759e7922b68',
    messagingSenderId: '745130635449',
    projectId: 'municipalgo-mobile',
    authDomain: 'municipalgo-mobile.firebaseapp.com',
    storageBucket: 'municipalgo-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVpYKYYruh58aoArk11REtv32l9D3WuY',
    appId: '1:745130635449:android:fd4f5884ac60523a922b68',
    messagingSenderId: '745130635449',
    projectId: 'municipalgo-mobile',
    storageBucket: 'municipalgo-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLclVSCZPYnGMyBbZLo4WiYIs2Ds2r7D4',
    appId: '1:745130635449:ios:8f2b3a8caf515e94922b68',
    messagingSenderId: '745130635449',
    projectId: 'municipalgo-mobile',
    storageBucket: 'municipalgo-mobile.firebasestorage.app',
    iosBundleId: 'com.example.municipalgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLclVSCZPYnGMyBbZLo4WiYIs2Ds2r7D4',
    appId: '1:745130635449:ios:8f2b3a8caf515e94922b68',
    messagingSenderId: '745130635449',
    projectId: 'municipalgo-mobile',
    storageBucket: 'municipalgo-mobile.firebasestorage.app',
    iosBundleId: 'com.example.municipalgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Ew8Bc8_9umuShCYwke5c7zdWxItMu34',
    appId: '1:745130635449:web:73ba4f64caf48cc6922b68',
    messagingSenderId: '745130635449',
    projectId: 'municipalgo-mobile',
    authDomain: 'municipalgo-mobile.firebaseapp.com',
    storageBucket: 'municipalgo-mobile.firebasestorage.app',
  );
}
